
import DisplayNavbar from '@/components/Navbar/Navbar'
import './globals.css'
import Providers from './providers'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body >
        <Providers >
          <div className="mx-auto max-w-4xl">
            <DisplayNavbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>

  );
}

