import DisplayNavbar from '@/components/Navbar/Navbar';
import './globals.css';
import Providers from './providers';
import { CartProvider } from '@/components/Cart/contexts/CartContext';
import Footer from '@/components/Footer/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className=''>
        <Providers>
          <CartProvider>
          <DisplayNavbar />
          <div className=''>{children}</div>
          <Footer />
          </CartProvider>
        </Providers>
      </body>
    </html>
  );
}
